import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@unocss/reset/sanitize/sanitize.css";
import "@unocss/reset/sanitize/assets.css";
import "./global.scss";
import favicon from "./favicon.svg";
import classnames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // <link rel="icon" href="/favicon.ico" />
  icons: {
    icon: favicon.src,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh" style={{ fontSize: "4px" }}>
      <body
        className={classnames([
          inter.className,
          "bg-#F6F5FA",
          "text-size-16px",
        ])}
      >
        <div id="app" className="max-w-1600px m-auto">
          {children}
        </div>
      </body>
    </html>
  );
}

export const dynamic = "error";
// // 禁用缓存
// export const fetchCache = "force-no-store";
