import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { Sider } from './layout-component/sider';
import { Right } from './layout-component/right';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className="bg-#F6F5FA max-1400px mx-auto">
        <div className="flex">
          <Sider></Sider>
          <main className="flex-1">{children}</main>
          <Right></Right>
        </div>
      </body>
    </html>
  );
}

export const dynamic = 'error';
