name: Deploy Blog

on:
  # 允许您在 Actions 页面手动触发此工作流
  workflow_dispatch:

  # 当您的 Issues 发生任何变化时，自动触发
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]

# 授予工作流部署到 GitHub Pages 的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 优化：避免因快速连续操作（如创建、打标签、编辑）导致的重复构建
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: bosens-China/yliu-blog-engine@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_BLOG_TITLE: "小🐑的博客"
          NEXT_PUBLIC_FOOTER_TEXT: "© 2025 by 小🐑"
