# 触发的事件
on: [issues, push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: use git
      uses: actions/setup-git@v1 
    - name: npm install, build, and test
      run: |
        npm npm install
        npm run build
      env:
        CI: true